export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_EMAIL_VALUE = "SET_EMAIL_VALUE";
export const SET_MODAL_STATE = "SET_MODAL_STATE";
export const SET_MODAL_SHARE_STATE = "SET_MODAL_SHARE_STATE";
export const INCREAS_PAGES_COUNT = "INCREAS_PAGES_COUNT";
export const REFRESH_PAGES_COUNT= "REFRESH_PAGES_COUNT";
export const SET_FAVORITE_MOVIES_ID= "SET_FAVORITE_MOVIES_ID";
export const REMOVE_FAVORITE_MOVIES_ID= "REMOVE_FAVORITE_MOVIES_ID";

