export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_MODAL_STATE = "SET_MODAL_STATE";
export const INCREAS_PAGES_COUNT = "INCREAS_PAGES_COUNT";
export const REFRESH_PAGES_COUNT= "REFRESH_PAGES_COUNT";

