export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USERNAME = "SET_USERNAME";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";