export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USERNAME = "SET_USERNAME";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";